### ISSUE TITLE
license

### ISSUE THREAD

**Issue by bertrandmartel** [zfanta/react-sequence-diagram#1]
Hi great job for porting js sequence diagram to reactJS !

I've noticed this is release under MIT in [npm](https://www.npmjs.com/package/react-sequence-diagram). Could you possibly add a license file in the repo ?

Thanks a lot !

**Comment by zfanta** [comment]
Thanks.

I added LICENSE file but I had to change license from MIT to BSD 2-clause, because [bramp/js-sequence-diagrams](https://github.com/bramp/js-sequence-diagrams) is licensed under the BSD 2-clause.
