### ISSUE TITLE
version 0.0.7 not rendering svg

### ISSUE THREAD

**Issue by bertrandmartel** [zfanta/react-sequence-diagram#2]
Hi again, I noticed that in the new version 0.0.7, `componentDidUpdate` method of SequenceDiagram has changed and `drawSVG` is not called anymore. I've noticed this change between 0.0.6 & 0.0.7: 
```
 class SequenceDiagram extends Component {
+  componentDidUpdate() {
+    if (!this.div) return;
+
+    const { input, options } = this.props;
+    this.div.removeChild(this.div.children[0]);
+    const diagram = Diagram.parse(input);
+    diagram.drawSVG(this.div, options)
+  }
+
   componentDidMount() {
     const { input, options } = this.props;
     const diagram = Diagram.parse(input);
```
It doesn't appear in your Github repo. Is this intended ?

Thanks

**Comment by zfanta** [comment]
Reinstalling the package may solve that problem. I removed that code in 0.0.7. compare [0.0.6.tgz](https://registry.npmjs.org/react-sequence-diagram/-/react-sequence-diagram-0.0.6.tgz) and [0.0.7.tgz](https://registry.npmjs.org/react-sequence-diagram/-/react-sequence-diagram-0.0.7.tgz).

Thanks again.
